FRONTEND::Routes: Implemented Register route
Elohim2598/ai_chatbot pull request #30
Opened 2024-06-17 21:54 UTC by Elohim2598

2024-06-19 00:31 UTC, j-eick approved these changes
Looks good. I didn't check every line though.

2024-06-19 12:01 UTC, adan-ayaz-stan requested changes

2024-06-19 12:01 UTC, adan-ayaz-stan commented on frontend/src/routes/auth/register/+page.svelte
Read the following things:
1. https://learn.svelte.dev/tutorial/form-validation
2. https://svelte-forms-lib-sapper-docs.vercel.app/introduction

Should make it a lot easier and less of a headache but still a headache :D.

2024-06-21 01:19 UTC, j-eick requested changes

2024-06-21 01:19 UTC, j-eick commented on frontend/src/components/ui/button/Button.svelte
> +	export let size: string = 'edium';
That's supposed to be **"medium"** I think.

2024-06-24 22:52 UTC, j-eick approved these changes
Looks good. 

Sidenote:
Whenever I use `flex justify-center items-center` I sometimes consider using `grid place-items-center` instead, as it's a bit less to type. Anyways...

2024-07-07 10:36 UTC, merged